# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: HaynesLab
email: admin@haynesnetwork.com
description: >- # this means to ignore newlines until "baseurl:"
  Site about my home lab!
#baseurl: /haynes43.github.io # the subpath of your site, e.g. /blog
#url: https://hayneslab.net # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: thayneslab
github_username:  thaynes43

# Build settings
#theme: minima
#remote_theme: pages-themes/slate@v0.2.0
#theme: jekyll-theme-midnight
remote_theme: mmistakes/minimal-mistakes@4.26.1
minimal_mistakes_skin: dark # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

social:
  type: Person # Person or Organization (defaults to Person)
  name: Tom Haynes # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/yourTwitter"
    - "https://www.facebook.com/yourFacebook"
    - "https://instagram.com/yourProfile"
    - "https://www.linkedin.com/in/yourprofile"

defaults:
  # _pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: labnav
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: false
      related: true
  # docs
  - scope:
      path: docs
      type: pages
    values:
      layout: single
      sidebar:
        nav: adventuresnav
  # cheatsheets
  - scope:
      path: cheatsheets
      type: pages
    values:
      layout: single
      sidebar:
        nav: sheetsnav
  # hardware
  - scope:
      path: hardware
      type: pages
    values:
      layout: single
      sidebar:
        nav: hardwarenav

enable_copy_code_button: true
#paginate: 5